{
    "name": "EasyTier",
    "description": "EasyTier VPN for RT-AC68U",
    "version": "1.0.0",
    "model": "RT-AC68U",
    "arch": "armv7l",
    "author": "Personal",
    "home_url": "Module_easytier.asp",
    "port": "8080",
    "server": "None",
    "module": "easytier",
    "category": "VPN",
    "type": "application",
    "exclusive": true,
    "forced_install": false,
    "depends": "",
    "rc_support": "startstop",
    "app_id": "easytier",
    "app_name": "EasyTier",
    "enable": "true"
}
